services:
    app:
        build:
            context: .
            target: serve
        ports:
            - 4000:4000
        environment:
            - JWT_SECRET=supersecret
        volumes:
            - ./src:/app/src
            - ./build:/app/build
        depends_on:
            mysql:
                condition: service_healthy
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: supersecret
            MYSQL_DATABASE: test
        volumes: 
            - /var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10